name: "Formatter"
description: "Format filenames into the format acceptable by TheAlgorithms opganisation"
author: "tjgurwara99"
inputs:
  filetypes:
    description: Filter files by specified file types (comma separated values in a string.) Maximum two values, example .cpp,.hpp
    required: true
  working-directory:
    description: Working directory of the formatter
    required: false
    default: .
  ignore-files:
    description: Files that should be ignored
    required: false
runs:
  using: composite
  steps:
    - name: Running the formatter
      shell: bash
      run: |
        ./filename_formatter.sh ${{ inputs.working-directory }} ${{ inputs.filetypes }} ${{ inputs.ignore-files }}
