name: Test with ignore directory argument
on: workflow_dispatch
jobs:
  formatter:
    runs-on: ubuntu-latest
    name: Verify that the filename formatter works (ignoring directory is included)
    steps:
      - uses: actions/checkout@v3
      - uses: ./formatter
        with:
          filetypes: .cpp,.hpp
          working-directory: .
          ignore-files: ./test
