name: Test without ignore directory argument
on: workflow_dispatch
jobs:
  formatter:
    runs-on: ubuntu-latest
    name: Verify that the filename formatter works
    steps:
      - uses: actions/checkout@v3
      - uses: ./formatter
        with:
          filetypes: .cpp,.hpp
          working-directory: ./test
